apiVersion: v1
kind: Service
metadata:
  name: spendsmart-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spendsmart
  ports:
    - port: 80          # Puerto EXTERNO (Libre en tu PC)
      targetPort: 8080  # Puerto INTERNO del contenedor (.NET escucha aquí)
      protocol: TCP